### ISSUE TITLE
Genetic_AI players not recognizing mates in one

### ISSUE THREAD

**Issue by MarkZH** [MarkZH/Genetic_Chess#15]
Two examples:

```
[White "Genetic AI 18419"]
[Black "Genetic AI 18465"]
[Result "0-1"]

1. e4 e5
2. Qh5 g5
3. Bb5 c6
4. Bc4 d5
5. Be2 dxe4
6. Kf1 Bb4
7. d4 exd3
8. Bf3 e4
9. Bxe4 Bd7
10. Be3 Nf6
11. Qxg5 Nxe4
12. Qxd8+ Kxd8
13. h4 Kc8
14. cxd3 Nd2+
15. Nxd2 Bg4
16. f3 Be6
17. Ne4 Kd8
18. Ne2 c5
19. Nf6 Nc6
20. Bf4 Kc8
21. Rc1 c4
22. g4 Bc5
23. Kg2 c3
24. Rxc3 Bb6
25. d4 Kd8
26. Bd6 Ne7
27. Rd1 Bxa2
28. g5 Be6
29. Kh2 h5
30. Ra1 a5
31. g6 fxg6
32. f4 Bf5
33. Rg1 Ba7
34. Bc7+ Kc8
35. Bb6+ Nc6
36. Bxa7 Rxa7
37. Ra1 Kb8
38. d5 Nb4
39. Nd4 b6
40. Nxf5 gxf5
41. Re1 Rg7
42. Nd7+ Rxd7
43. Rg1 Kb7
44. Rg6 Ka7
45. Rc7+ Rxc7
46. Rg2 Re8
47. d6 Rd7
48. Rd2 Re3
49. b3 Rg7
50. Rf2 Kb8
51. d7 Rxd7
52. Rg2 Kb7
53. Rf2 Rc3
54. Re2 Ka6
55. Rf2 Kb7
56. Re2 Ka6
57. Rf2 Ka7
58. Re2 Kb7
59. Rf2 Rd8
60. Re2 Ka6
61. Rg2 Rd7
62. Re2 Rc8
63. Re8 Rxe8
64. Kg2 Re2+
65. Kf3 Rdd2
66. Kg3 Nc2
67. Kh3 a4
68. Kg3 a3
69. Kh3 a2
70. Kg3 a1=R
71. Kh3 Ra2
72. Kg3 Ra1
73. Kh3 Ra2
74. Kg3 Ra3
75. Kh3 Ra1
76. Kg3 Ra2
77. Kh3 Ra1
78. Kg3 Ra2
79. Kh3 Ra3
80. Kg3 Ra4
81. Kh3 Ra3
82. Kg3 Ra4
83. Kh3 Ra5
84. Kg3 Ra3
85. Kh3 Ra4
86. Kg3 Ra5
87. Kh3 Ra4
88. Kg3 Ra5
89. Kh3 Rb5
90. Kg3 Ka7
91. Kh3 Ka6
92. Kg3 Ka7
93. Kh3 Kb7
94. Kg3 Ra5
95. Kh3 Ra4
96. Kg3 Ra3
97. Kh3 Ra2
98. Kg3 Ra1
99. Kh3 Ra2
100. Kg3 Ra1
101. Kh3 Ra3
102. Kg3 Ra2
103. Kh3 Ra1
104. Kg3 Ra2
105. Kh3 Ra1
106. Kg3 Ra3
107. Kh3 Ra4
108. Kg3 Ra5
109. Kh3 Ra3
110. Kg3 Ra6
111. Kh3 Ra5
112. Kg3 Ra6
113. Kh3 Ra5
114. Kg3 Ra7
115. Kh3 Ra6
116. Kg3 Ra7
117. Kh3 Ra6
118. Kg3 Ra8
119. b4 Ra7
120. b5 Ra5
121. Kh3 Ra4
122. Kg3 Ra3#	0-1


{ Initial time: 300 }
{ Moves to reset clocks: 0 }
{ Time left: White: 0.156967 }
{            Black: 7.10659 }
```

Black should have mated with `75. ... Rxb3#` (on several occasions), or `119. Ra3#` (which it finally found on the last move).

Another example:

```
[White "Genetic AI 18374"]
[Black "Genetic AI 18468"]
[Result "1-0"]

1. e4 e5
2. Qh5 g5
3. Bb5 c6
4. Bc4 d5
5. exd5 Bf5
6. d6 Qxd6
7. Qxf7+ Kd8
8. Qxf5 Bg7
9. Qxg5+ Ne7
10. Qxg7 Re8
11. d3 Qb4+
12. Nc3 Nd5
13. Bg5+ Kc8
14. Bxd5 cxd5
15. Kf1 Qg4
16. Nxd5 Na6
17. Nb6+ axb6
18. Qxh7 Qxg5
19. Qh3+ Kd8
20. g3 Nc7
21. Re1 Rxa2
22. Qh7 Rxb2
23. Qf7 Rh8
24. h4 Qg4
25. Qf6+ Kd7
26. Qxh8 Rxc2
27. Qh7+ Ke6
28. Qh6+ Kf7
29. Qh7+ Kf6
30. Qh6+ Qg6
31. Qf8+ Ke6
32. Qc8+ Kf6
33. Qf8+ Ke6
34. Qc8+ Kf6
35. Qd8+ Ke6
36. Rxe5+ Kxe5
37. Nf3+ Ke6
38. Nd4+ Kf7
39. Nxc2 Ne6
40. Qd7+ Kf6
41. Ke1 Nf8
42. Qd6+ Ne6
43. Ne3 Qg7
44. Kd2 b5
45. Ra1 b4
46. Qxb4 Qh6
47. Qc3+ Kf7
48. f4 Qh5
49. g4 Qxh4
50. Qc4 Qh2+
51. Kd1 Qh1+
52. Nf1 Qxf1+
53. Kd2 Qxa1
54. g5 Qb2+
55. Ke3 Qd4+
56. Qxd4 Nxd4
57. Kxd4 Ke6
58. g6 Kf6
59. Kd5 Kxg6
60. Ke6 Kg7
61. f5 Kh6
62. Kf6 Kh5
63. Kg7 Kg5
64. f6 Kh5
65. f7 Kh4
66. Kg6 Kh3
67. Kg5 Kh2
68. Kg4 Kh1
69. f8=Q Kg2
70. Qf3+ Kh2
71. Qxb7 Kg1
72. Qb2 Kh1
73. Kf3 Kg1
74. Qa2 Kh1
75. Qb2 Kg1
76. Qa2 Kh1
77. Qc2 Kg1
78. Qb2 Kh1
79. Qa2 Kg1
80. Qb2 Kh1
81. Qa2 Kg1
82. Qc2 Kh1
83. Qd2 Kg1
84. Qc2 Kh1
85. Qd2 Kg1
86. Qe2 Kh1
87. d4 Kg1
88. d5 Kh1
89. d6 Kg1
90. d7 Kh1
91. d8=R Kg1
92. Rc8 Kh1
93. Rb8 Kg1
94. Ra8 Kh1
95. Ra7 Kg1
96. Ra6 Kh1
97. Ra5 Kg1
98. Ra4 Kh1
99. Ra3 Kg1
100. Ra2 Kh1
101. Ra1#	1-0


{ Initial time: 300 }
{ Moves to reset clocks: 0 }
{ Time left: White: 5.67565 }
{            Black: 16.5472 }
```
White should have mated many times starting at `74. Rf2#` or `74. Rg2#`.

**Comment by MarkZH** [comment]
Suspicion: look ahead is a depth-first search. In both cases, the side to eventually lose only had one move, so the look ahead automatically made that move and considered the next set of moves, the first of which also an ineffective move that left one move for the losing side. Thus, with little time remaining, the winning side didn't have enough time to evaluate every move.

Possible solution (pending proof by analysis mentioned in issue #13): make look ahead breadth-first. Instead of recursing, have a queue of hypothetical boards to analyze paired with the number of positions to examine (`std::vector<std::pair<Board, int>>`).

Second possible solution: sort the moves to consider by `genome.evaluate()`.

Third solution: maintain a memoization of `Board` states already considered (will need some way of maintaining a count so 50-move and 3-fold stalemates are considered).

**Comment by MarkZH** [comment]
Note for breadth-first solution above: the index of the previous board will have to be stored as well in the queue. So, the queue will most likely be something like: `std::vector<std::tuple<Board, int, size_t>>` where the `int` is the number of positions to examine for that board and the `size_t` is the index of the preceding `Board`.

**Comment by MarkZH** [comment]
Add to the above comment the current best move and associated best score (essentially, the entire contents of the stack frame in the recursive solution).

In lieu of further corrections, just note that this is starting to look like it needs a `struct` for structure, if not an entire `class`.

**Comment by MarkZH** [comment]
At least part of the problem comes from `Genome::evaluate()` returning `lowest()` for stalemates. As the score propagates back up the call stack, it flips between the maximum and minimum finite values, since a score from the opposite perspective is assumed to simply be the negative. If the opposite side evaluation finds the stalemate, that move will be preferable to every other non-game-ending move.

Consider returning NaN for stalemate. Since stalemate is preferable to loss, will need extra logic so NaN > -inf without changing the best score.

Since the issue here says that mates in one are not found, this may not be the entire solution.

**Comment by MarkZH** [comment]
Also consider 0 or a genetically determined value for stalemate.

**Comment by MarkZH** [comment]
Ignore the last comment. Both sides of a stalemate have an equally dim view of the outcome. Use NaN.

**Comment by MZHarrison** [comment]
To add to the first comment, the first game should have ended with `66. ... Rd3` or `66. ... Re3`.

**Comment by MarkZH** [comment]
Difficult to test since every game is different, even between the same players with the same time limit.

**Comment by MarkZH** [comment]
Another example. Game should have ended with `79. Rh7`
```
[White "Genetic AI 2439"]
[Black "Genetic AI 2519"]
[Round "3206"]
[Result "1-0"]

1. e4 h5
2. d4 g5
3. Qxh5 e5
4. Qxf7+ Kxf7
5. c3 d5
6. h4 c5
7. Bxg5 Qxg5
8. hxg5 b5
9. Bxb5 a5
10. dxe5 d4
11. cxd4 c4
12. Bxc4+ Ke8
13. Bb5+ Kd8
14. Nc3 a4
15. Rxh8 a3
16. bxa3 Bg7
17. Rxg8+ Bf8
18. Rxf8+ Ke7
19. Re8+ Kf7
20. e6+ Bxe6
21. g6+ Kxg6
22. Rxe6+ Kh7
23. Re7+ Kh8
24. Re8+ Kh7
25. Re7+ Kh8
26. Re8+ Kh7
27. Rh8+ Kg7
28. f4 Kf7
29. Rh7+ Kg8
30. Bc4+ Kf8
31. Rh8+ Kg7
32. Rg8+ Kh7
33. Rh8+ Kg7
34. Rg8+ Kh7
35. Rh8+ Kg6
36. f5+ Kg7
37. Rg8+ Kh7
38. Rg7+ Kh6
39. Rg6+ Kh7
40. Bg8+ Kh8
41. a4 Nd7
42. Rh6+ Kxg8
43. Rg6+ Kh8
44. Rh6+ Kg8
45. Rg6+ Kh8
46. Rh6+ Kg7
47. Rg6+ Kf8
48. a3 Rc8
49. Rb1 Rxc3
50. Rg8+ Kf7
51. Rf8+ Kg7
52. Rg8+ Kf7
53. Rf8+ Kg7
54. Rg8+ Kh6
55. Rh8+ Kg5
56. Rg8+ Kh6
57. Rh8+ Kg5
58. Rg8+ Kh4
59. g3+ Kh5
60. g4+ Kh4
61. Rh8+ Kg5
62. Rg8+ Kh4
63. Rh8+ Kg5
64. Rg8+ Kf4
65. Ne2+ Kf3
66. Nxc3 Kf4
67. Kf2 Nf6
68. a5 Nh7
69. a6 Nf6
70. Nd5+ Kxe4
71. Nxf6+ Kf4
72. Rh8 Kg5
73. a7 Kxf6
74. a4 Kf7
75. g5 Ke7
76. Rb6 Kf7
77. a8=R Kg7
78. a5 Kf7
79. a6 Kg7
80. a7 Kf7
81. Rab8 Kg7
82. a8=R Kf7
83. Ra7#	1-0


{ Initial time: 300 }
{ Moves to reset clocks: 0 }
{ Time left: White: 12.4315 }
{            Black: 64.9962 }

```

```
ID: 2439

Name: Piece Strength Gene
B: 1.91186
N: 0.24928
P: -0.120442
Q: -1.78119
R: -1.46189
INACTIVE

Name: Look Ahead Gene
Mean Game Length: 47.7601
Positions Per Second: 22.1855
ACTIVE

Name: Total Force Gene
Scalar: 30.8767
ACTIVE

Name: Freedom to Move Gene
Scalar: 144.265
ACTIVE

Name: Pawn Advancement Gene
Scalar: 35.4546
ACTIVE

Name: Opponent Pieces Targeted
Scalar: 17.4125
ACTIVE

Name: Sphere of Influence Gene
Legal Bonus: 5.51433
Scalar: 70.055
INACTIVE

Name: King Confinement Gene
Scalar: -25.9889
INACTIVE

Name: King Protection Gene
Scalar: 76.4453
INACTIVE

END
```

```
ID: 2519

Name: Piece Strength Gene
B: 1.91186
N: 0.24928
P: -0.120442
Q: -1.78119
R: -1.46189
ACTIVE

Name: Look Ahead Gene
Mean Game Length: 47.7601
Positions Per Second: 22.1855
ACTIVE

Name: Total Force Gene
Scalar: 47.9553
ACTIVE

Name: Freedom to Move Gene
Scalar: 112.318
INACTIVE

Name: Pawn Advancement Gene
Scalar: 71.2595
ACTIVE

Name: Opponent Pieces Targeted
Scalar: 17.4125
INACTIVE

Name: Sphere of Influence Gene
Legal Bonus: 10.734
Scalar: -4.7136
INACTIVE

Name: King Confinement Gene
Scalar: -25.9889
INACTIVE

Name: King Protection Gene
Scalar: 5.65091
INACTIVE

END
```

**Comment by MarkZH** [comment]
Debugging step: load board state just before checkmate and make sure the board actually recognizes the next move as checkmate.

**Comment by MarkZH** [comment]
First debugging step complete (using commit 86c3492fef9396fede2851ee87e35c04c3f5cd06). Program does recognize `79. Rh7` as checkmate. So, somehow, Genetic_AI is missing this move.

**Comment by MarkZH** [comment]
An explanation of the fix:

After the fix, if submitting a move causes a `Checkmate_Exception` to be thrown, that move is immediately returned. Previously, it was assigned a score of infinity and compared with other moves. If a move considered later resulted in checkmate several moves ahead, that move would also get a score of infinity and be considered the best move. The early return for an immediate checkmate fixes the problem.
