### ISSUE TITLE
Consider removing the throwing of exceptions to indicate the end of a game

### ISSUE THREAD

**Issue by MZHarrison** [MarkZH/Genetic_Chess#17]
See if there is a performance issue or if the code becomes easier to read.

**Comment by MarkZH** [comment]
Put `Scoped_Stopwatch` at beginning of `submit_move()` and just inside `if(no_legal_moves())` block.

**Comment by MarkZH** [comment]
There's no issue here.  The endgame block where exceptions are thrown takes less than 5% the normal time of a submit move.
